version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_test
    ports:
      - "3306:3306"
